"""phase-15f brain regions + 3-layer market + migration_hash fields

Revision ID: 0aee66b5fe07
Revises: a8f3b9e21c47
Create Date: 2026-07-29 09:16:18.899531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aee66b5fe07'
down_revision: Union[str, None] = 'a8f3b9e21c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_genes',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gene_slugs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ai_genes_slug', 'ai_genes', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('base_classes',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_base_classes_slug', 'base_classes', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('capability_market',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_via', sa.String(length=20), nullable=False),
    sa.Column('source_entity_slug', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_capability_market_name', 'capability_market', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('brainstem_schedules',
    sa.Column('central_hub_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['central_hub_id'], ['blackboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cerebellum_agents',
    sa.Column('central_hub_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['central_hub_id'], ['blackboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_cerebellum_agents_active', 'cerebellum_agents', ['central_hub_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_table('frontal_lobe_kanbans',
    sa.Column('central_hub_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee_employee_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['central_hub_id'], ['blackboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_frontal_lobe_kanbans_hub_position', 'frontal_lobe_kanbans', ['central_hub_id', 'position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('employees', sa.Column('migration_hash', sa.String(length=64), nullable=True))
    op.add_column('employees', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('employees', sa.Column('prompt_regen_snapshot', sa.Text(), nullable=True))
    op.add_column('instances', sa.Column('active_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'active_hash')
    op.drop_column('employees', 'prompt_regen_snapshot')
    op.drop_column('employees', 'capabilities')
    op.drop_column('employees', 'migration_hash')
    op.drop_index('uq_frontal_lobe_kanbans_hub_position', table_name='frontal_lobe_kanbans', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('frontal_lobe_kanbans')
    op.drop_index('uq_cerebellum_agents_active', table_name='cerebellum_agents', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_table('cerebellum_agents')
    op.drop_table('brainstem_schedules')
    op.drop_index('uq_capability_market_name', table_name='capability_market', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('capability_market')
    op.drop_index('uq_base_classes_slug', table_name='base_classes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('base_classes')
    op.drop_index('uq_ai_genes_slug', table_name='ai_genes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('ai_genes')
    # ### end Alembic commands ###
