"""core domain models

Revision ID: 377afa41306b
Revises: 
Create Date: 2026-07-24 14:58:27.949877

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '377afa41306b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_presets',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_employee_presets_slug', 'employee_presets', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('employees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('preset_slug', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('display_color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_employees_slug', 'employees', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('offices',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('blackboard_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_offices_slug', 'offices', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_username', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('blackboards',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_blackboards_office', 'blackboards', ['office_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('instances',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=True),
    sa.Column('proxy_token', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_instances_workspace_path', 'instances', ['workspace_path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND workspace_path IS NOT NULL'))
    op.create_table('memory_entries',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_instance_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_entries_employee_created', 'memory_entries', ['employee_id', 'created_at'], unique=False)
    op.create_table('vaults',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_vaults_office', 'vaults', ['office_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('blackboard_files',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_path', sa.String(length=1024), nullable=True),
    sa.Column('storage_key', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('uploader_user_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_instance_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(uploader_user_id IS NOT NULL) <> (uploader_instance_id IS NOT NULL)', name='ck_blackboard_files_exclusive_uploader'),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['uploader_instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_blackboard_files_path', 'blackboard_files', ['office_id', 'parent_path', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_blackboard_files_storage_key', 'blackboard_files', ['storage_key'], unique=True)
    op.create_table('memberships',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('hex_q', sa.Integer(), nullable=False),
    sa.Column('hex_r', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL) <> (instance_id IS NOT NULL)', name='ck_memberships_exclusive_fk'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_memberships_office_instance', 'memberships', ['office_id', 'instance_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND instance_id IS NOT NULL'))
    op.create_index('uq_memberships_office_user', 'memberships', ['office_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND user_id IS NOT NULL'))
    op.create_table('vault_entries',
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('archived_key', sa.String(length=255), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corridors',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('from_membership_id', sa.String(length=36), nullable=False),
    sa.Column('to_membership_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('edge_meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['to_membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_corridors_active_edge', 'corridors', ['office_id', 'from_membership_id', 'to_membership_id'], unique=True, postgresql_where=sa.text('is_active IS TRUE AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_corridors_active_edge', table_name='corridors', postgresql_where=sa.text('is_active IS TRUE AND deleted_at IS NULL'))
    op.drop_table('corridors')
    op.drop_table('vault_entries')
    op.drop_index('uq_memberships_office_user', table_name='memberships', postgresql_where=sa.text('deleted_at IS NULL AND user_id IS NOT NULL'))
    op.drop_index('uq_memberships_office_instance', table_name='memberships', postgresql_where=sa.text('deleted_at IS NULL AND instance_id IS NOT NULL'))
    op.drop_table('memberships')
    op.drop_index('uq_blackboard_files_storage_key', table_name='blackboard_files')
    op.drop_index('uq_blackboard_files_path', table_name='blackboard_files', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('blackboard_files')
    op.drop_index('uq_vaults_office', table_name='vaults', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('vaults')
    op.drop_index('ix_memory_entries_employee_created', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index('uq_instances_workspace_path', table_name='instances', postgresql_where=sa.text('deleted_at IS NULL AND workspace_path IS NOT NULL'))
    op.drop_table('instances')
    op.drop_index('uq_blackboards_office', table_name='blackboards', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('blackboards')
    op.drop_index('uq_users_username', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('uq_offices_slug', table_name='offices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('offices')
    op.drop_index('uq_employees_slug', table_name='employees', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('employees')
    op.drop_index('uq_employee_presets_slug', table_name='employee_presets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('employee_presets')
    # ### end Alembic commands ###
