"""add knowledge entries and dimensions tables

Revision ID: 52f2a74e4c34
Revises: 794abeff4722
Create Date: 2026-08-03 22:17:19.737776

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52f2a74e4c34'
down_revision: Union[str, None] = '794abeff4722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Existence guards — this revision must run on BOTH paths:
#   A) a database at 794abeff4722 (tables do not exist yet), and
#   B) a fresh database where b1c2d3e4f5a6 already rebuilt the full schema
#      from live model metadata (Base.metadata.create_all), which pre-creates
#      knowledge_entries / knowledge_dimensions (and their indexes).
# ---------------------------------------------------------------------------


def _has_table(bind, table: str) -> bool:
    return table in set(sa.inspect(bind).get_table_names())


def _has_index(bind, table: str, index: str) -> bool:
    if not _has_table(bind, table):
        return False
    return index in {ix["name"] for ix in sa.inspect(bind).get_indexes(table)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if not _has_table(bind, 'knowledge_dimensions'):
        op.create_table('knowledge_dimensions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), server_default='org', nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('namespace_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope IN ('system', 'org', 'namespace', 'workspace')", name='ck_knowledge_dimensions_scope'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not _has_index(bind, 'knowledge_dimensions', 'ix_knowledge_dimensions_scope_org'):
        op.create_index('ix_knowledge_dimensions_scope_org', 'knowledge_dimensions', ['scope', 'organization_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    if not _has_index(bind, 'knowledge_dimensions', 'uq_knowledge_dimensions_active_slug'):
        op.create_index('uq_knowledge_dimensions_active_slug', 'knowledge_dimensions', ['scope', sa.literal_column("COALESCE(organization_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(namespace_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(workspace_id, '00000000-0000-0000-0000-000000000000')"), 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    if not _has_table(bind, 'knowledge_entries'):
        op.create_table('knowledge_entries',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=20), server_default='org', nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('namespace_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope IN ('system', 'org', 'namespace', 'workspace')", name='ck_knowledge_entries_scope'),
    sa.ForeignKeyConstraint(['dimension_id'], ['knowledge_dimensions.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_entity_id'):
        op.create_index('ix_knowledge_entries_entity_id', 'knowledge_entries', ['entity_id'], unique=False, postgresql_where=sa.text('entity_id IS NOT NULL'))
    if not _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_scope_org'):
        op.create_index('ix_knowledge_entries_scope_org', 'knowledge_entries', ['scope', 'organization_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    if not _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_workspace_key'):
        op.create_index('ix_knowledge_entries_workspace_key', 'knowledge_entries', ['workspace_id', 'key'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    if not _has_index(bind, 'knowledge_entries', 'uq_knowledge_entries_active_key'):
        op.create_index('uq_knowledge_entries_active_key', 'knowledge_entries', ['scope', sa.literal_column("COALESCE(organization_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(namespace_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(workspace_id, '00000000-0000-0000-0000-000000000000')"), 'key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if _has_index(bind, 'knowledge_entries', 'uq_knowledge_entries_active_key'):
        op.drop_index('uq_knowledge_entries_active_key', table_name='knowledge_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    if _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_workspace_key'):
        op.drop_index('ix_knowledge_entries_workspace_key', table_name='knowledge_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    if _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_scope_org'):
        op.drop_index('ix_knowledge_entries_scope_org', table_name='knowledge_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    if _has_index(bind, 'knowledge_entries', 'ix_knowledge_entries_entity_id'):
        op.drop_index('ix_knowledge_entries_entity_id', table_name='knowledge_entries', postgresql_where=sa.text('entity_id IS NOT NULL'))
    if _has_table(bind, 'knowledge_entries'):
        op.drop_table('knowledge_entries')
    if _has_index(bind, 'knowledge_dimensions', 'uq_knowledge_dimensions_active_slug'):
        op.drop_index('uq_knowledge_dimensions_active_slug', table_name='knowledge_dimensions', postgresql_where=sa.text('deleted_at IS NULL'))
    if _has_index(bind, 'knowledge_dimensions', 'ix_knowledge_dimensions_scope_org'):
        op.drop_index('ix_knowledge_dimensions_scope_org', table_name='knowledge_dimensions', postgresql_where=sa.text('deleted_at IS NULL'))
    if _has_table(bind, 'knowledge_dimensions'):
        op.drop_table('knowledge_dimensions')
    # ### end Alembic commands ###
