"""add instance_provider_configs table

Revision ID: 5bfdb22e9d96
Revises: f31147674437
Create Date: 2026-07-27 23:36:56.122702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfdb22e9d96'
down_revision: Union[str, None] = 'f31147674437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_provider_configs',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('api_key_ref', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('selected_models', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_instance_provider_configs_instance_type', 'instance_provider_configs', ['instance_id', 'provider_type'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_instance_provider_configs_instance_type', table_name='instance_provider_configs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('instance_provider_configs')
    # ### end Alembic commands ###
