"""add dimension_id to knowledge entries unique index

Revision ID: 94553816102e
Revises: 52f2a74e4c34
Create Date: 2026-08-03 23:11:36.356329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94553816102e'
down_revision: Union[str, None] = '52f2a74e4c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_knowledge_entries_active_key'), table_name='knowledge_entries', postgresql_where='(deleted_at IS NULL)')
    op.create_index('uq_knowledge_entries_active_key', 'knowledge_entries', ['scope', sa.literal_column("COALESCE(organization_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(namespace_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(workspace_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(dimension_id, '00000000-0000-0000-0000-000000000000')"), 'key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_knowledge_entries_active_key', table_name='knowledge_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_knowledge_entries_active_key'), 'knowledge_entries', ['scope', sa.literal_column("COALESCE(organization_id, '00000000-0000-0000-0000-000000000000'::character varying)"), sa.literal_column("COALESCE(namespace_id, '00000000-0000-0000-0000-000000000000'::character varying)"), sa.literal_column("COALESCE(workspace_id, '00000000-0000-0000-0000-000000000000'::character varying)"), 'key'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
