"""add meetings tables

Revision ID: 9536991c7a95
Revises: d0bcf3d3039f
Create Date: 2026-08-05 11:59:09.928568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9536991c7a95'
down_revision: Union[str, None] = 'd0bcf3d3039f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(bind, table: str) -> bool:
    return table in set(sa.inspect(bind).get_table_names())


def _has_index(bind, table: str, index_name: str) -> bool:
    return index_name in {
        idx["name"] for idx in sa.inspect(bind).get_indexes(table)
    }


def upgrade() -> None:
    # Guarded: the PRD-v2 rebuild baseline (b1c2d3e4f5a6) runs
    # ``Base.metadata.create_all`` against live model metadata, so fresh
    # builds already contain these tables + their partial indexes before
    # this revision runs (same pattern as d0bcf3d3039f).
    if not _has_table(op.get_bind(), "meetings"):
        op.create_table('meetings',
        sa.Column('workspace_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('agenda', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table(op.get_bind(), "meeting_participants"):
        op.create_table('meeting_participants',
        sa.Column('meeting_id', sa.String(length=36), nullable=False),
        sa.Column('membership_id', sa.String(length=36), nullable=False),
        sa.Column('role_in_meeting', sa.String(length=100), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        # Partial unique indexes are NOT recreated by create_all on the
        # baseline rebuild path, so always ensure them here (guard by table
        # existence: the baseline rebuild created the table + indexes only
        # when it ran before this revision).
        op.create_index('uq_meeting_participants_meeting_membership', 'meeting_participants', ['meeting_id', 'membership_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
        op.create_index('uq_meeting_participants_meeting_role', 'meeting_participants', ['meeting_id', 'role_in_meeting'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND role_in_meeting IS NOT NULL'))
    if not _has_index(op.get_bind(), "brainstem_schedules", "ix_brainstem_schedules_enabled_next_run"):
        op.create_index('ix_brainstem_schedules_enabled_next_run', 'brainstem_schedules', ['enabled', 'next_run_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brainstem_schedules_enabled_next_run', table_name='brainstem_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_meeting_participants_meeting_role', table_name='meeting_participants', postgresql_where=sa.text('deleted_at IS NULL AND role_in_meeting IS NOT NULL'))
    op.drop_index('uq_meeting_participants_meeting_membership', table_name='meeting_participants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('meeting_participants')
    op.drop_table('meetings')
