"""add instance_loop_states table

Revision ID: bc3d9d6a84c8
Revises: 0b4e3562358d
Create Date: 2026-07-26 22:41:13.208254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3d9d6a84c8'
down_revision: Union[str, None] = '0b4e3562358d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_loop_states',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('loop_status', sa.String(length=20), nullable=False),
    sa.Column('current_plan_ref', sa.Text(), nullable=True),
    sa.Column('continuation_count', sa.Integer(), nullable=False),
    sa.Column('total_token_estimate', sa.Integer(), nullable=False),
    sa.Column('wall_clock_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checkpoint_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boulder_snapshot', sa.JSON(), nullable=True),
    sa.Column('notepad_refs', sa.JSON(), nullable=True),
    sa.Column('max_continuations', sa.Integer(), nullable=False),
    sa.Column('max_wall_clock_seconds', sa.Integer(), nullable=False),
    sa.Column('max_token_estimate', sa.Integer(), nullable=False),
    sa.Column('idle_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_loop_states_instance', 'instance_loop_states', ['instance_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_loop_states_instance', table_name='instance_loop_states', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('instance_loop_states')
    # ### end Alembic commands ###
