"""add instance_inject_queue table

Revision ID: d0bcf3d3039f
Revises: 2645619c35ad
Create Date: 2026-08-05 00:09:47.277317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0bcf3d3039f'
down_revision: Union[str, None] = '2645619c35ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(bind, table: str) -> bool:
    return table in set(sa.inspect(bind).get_table_names())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Guarded: the PRD-v2 rebuild baseline (b1c2d3e4f5a6) runs
    # ``Base.metadata.create_all`` against live model metadata, so fresh
    # builds already contain this table + index before this revision runs.
    if not _has_table(op.get_bind(), "instance_inject_queue"):
        op.create_table('instance_inject_queue',
        sa.Column('instance_id', sa.String(length=36), nullable=False),
        sa.Column('kind', sa.String(length=32), nullable=False),
        sa.Column('delivery_mode', sa.String(length=16), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.String(length=2000), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_instance_inject_queue_instance_status', 'instance_inject_queue', ['instance_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instance_inject_queue_instance_status', table_name='instance_inject_queue')
    op.drop_table('instance_inject_queue')
    # ### end Alembic commands ###
