"""Internal endpoints used by agent pods running in K8s mode.

These endpoints are NOT exposed publicly — they are only callable from
agent pods (or trusted local processes) that present the shared
``COCOA_API_TOKEN``. The token is generated by the backend lifespan on
startup and injected into instance pods by DeployService (P11c Todo 1).

Two surfaces:

* ``POST /api/v1/internal/events/emit`` — agent pod persists an audit
  event via the in-process :func:`app.core.events.emit` pipeline, which
  also fires the registered best-effort handlers.
* ``GET  /api/v1/internal/control/poll`` — agent pod polls the D11
  control-plane downlink (``harness.control_sent`` events) for its own
  ``instance_id``.

Both endpoints are gated by :func:`verify_internal_token`, which compares
the request's ``Authorization: Bearer <token>`` header against the
``COCOA_API_TOKEN`` environment variable using
:func:`secrets.compare_digest` (timing-safe).
"""

from __future__ import annotations

import os
import secrets

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from sqlalchemy import select

from app.api.deps import DB
from app.core.event_types import HARNESS_CONTROL_SENT
from app.core.events import emit
from app.core.inject_queue import ack_injects, poll_pending_injects
from app.models.event import Event
from app.schemas.internal import AckRequest

router = APIRouter(prefix="/internal", tags=["internal"])


async def verify_internal_token(request: Request) -> None:
    """Verify the Bearer token matches ``COCOA_API_TOKEN`` env var."""
    auth = request.headers.get("Authorization", "")
    expected = os.environ.get("COCOA_API_TOKEN", "")
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="COCOA_API_TOKEN not configured on backend",
        )
    if not auth.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="missing or malformed Authorization header",
        )
    token = auth[len("Bearer "):]
    if not secrets.compare_digest(token, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid internal token",
        )


@router.post(
    "/events/emit",
    status_code=201,
    dependencies=[Depends(verify_internal_token)],
)
async def internal_emit_event(body: dict, db: DB) -> dict:
    """Agent pod emits an event; backend persists via in-process emit path.

    Required JSON fields: ``type``, ``actor_type``, ``actor_id``,
    ``resource_type``, ``resource_id``, ``payload``. The handler chain
    registered against ``app.core.events`` runs synchronously before
    commit, exactly as it would for an in-process ``emit()`` call.
    """
    required = {
        "type",
        "actor_type",
        "actor_id",
        "resource_type",
        "resource_id",
        "payload",
    }
    if missing := required - set(body):
        raise HTTPException(
            status_code=400, detail=f"missing fields: {sorted(missing)}"
        )
    try:
        event = await emit(
            body["type"],
            actor_type=body["actor_type"],
            actor_id=body["actor_id"],
            resource_type=body["resource_type"],
            resource_id=body["resource_id"],
            payload=body["payload"],
            session=db,
        )
        await db.commit()
    except Exception as e:  # pragma: no cover — DB-level failure path
        raise HTTPException(status_code=500, detail=f"emit failed: {e!s}") from e
    return {"event_id": event.id if event else None}


@router.get(
    "/control/poll",
    dependencies=[Depends(verify_internal_token)],
)
async def internal_control_poll(
    db: DB,
    instance_id: str = Query(...),
    last_seen_id: int = Query(0, ge=0),
) -> dict:
    """Return recent ``harness.control_sent`` events + pending injects.

    ``last_seen_id`` is the caller-side cursor; ``0`` (the default) means
    "from the beginning".  Up to 50 events are returned per call,
    oldest-first, so the caller can resume from ``events[-1].id``. The
    ``injects`` field carries up to 20 pending (unexpired) v4.7 inject
    queue items for this instance; they are flipped to ``delivered`` in
    the same call so a subsequent poll does not repeat them.
    """
    stmt = (
        select(Event)
        .where(
            Event.resource_id == instance_id,
            Event.type == HARNESS_CONTROL_SENT,
            # Event.id is a UUID string; comparing against str(last_seen_id)
            # yields a stable lexicographic filter for the cursor.
            Event.id > str(last_seen_id),
        )
        .order_by(Event.id.asc())
        .limit(50)
    )
    result = await db.execute(stmt)
    events = list(result.scalars().all())
    injects = await poll_pending_injects(db, instance_id=instance_id, limit=20)
    await db.commit()
    return {
        "events": [
            {
                "id": e.id,
                "type": e.type,
                "payload": e.payload,
                "created_at": e.created_at,
            }
            for e in events
        ],
        "last_seen_id": events[-1].id if events else last_seen_id,
        "injects": [
            {
                "queue_id": q.id,
                "kind": q.kind,
                "delivery_mode": q.delivery_mode,
                "payload": q.payload,
                "tldr": (q.payload or {}).get("tldr"),
                "expires_at": q.expires_at,
            }
            for q in injects
        ],
    }


@router.post(
    "/control/ack",
    dependencies=[Depends(verify_internal_token)],
)
async def internal_control_ack(body: AckRequest, db: DB) -> dict:
    """Ack delivered inject queue rows; returns the acked count.

    soft_inject / wake acks emit ``harness.inject_applied`` (the service
    does this); notify acks only flip the row to ``acked``. Rows that are
    not in the ``delivered`` state are skipped, so acking is idempotent.
    """
    acked = await ack_injects(db, queue_ids=body.queue_ids)
    await db.commit()
    return {"acked": acked}
